# Generated by Django 3.0.4 on 2020-03-26 05:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getedge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdata',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
